logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://registry:8761/eureka/}

security:
  oauth2:
    resource:
      user-info-uri: ${AUTH_SERVICE_URI:http://auth-service:5000}/uaa/users/current

spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}