spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:auth-mongodb}
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017

server:
  servlet:
    context-path: /uaa
  port: 5001

logging:
  pattern:
    console: "[${spring.application.name},%X{traceId:-},%X{spanId:-},%X{exportable:-}] %-5level %logger{36} - %msg%n"