spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:auth-mongodb}
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017

server:
  servlet:
    context-path: /uaa
  port: 5001

hystrix:
  command:
    default:
      circuitBreaker:
        enabled: true
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 30000
  threadpool:
    default:
      coreSize: 100
      maxQueueSize: 10000
      queueSizeRejectionThreshold: 10000