hystrix:
  command:
    default:
      circuitBreaker:
        enabled: false  # 关闭全局熔断
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 80000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 0

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
        path: /uaa/**
        url: ${AUTH_SERVICE_URI:http://localhost:5000}
        stripPrefix: false
        sensitiveHeaders:

    account-service:
        path: /accounts/**
        serviceId: account-service
        stripPrefix: false
        sensitiveHeaders:

    statistics-service:
        path: /statistics/**
        serviceId: statistics-service
        stripPrefix: false
        sensitiveHeaders:

    notification-service:
        path: /notifications/**
        serviceId: notification-service
        stripPrefix: false
        sensitiveHeaders:

server:
  port: 4000

logging:
  level:
    org.springframework.cloud.netflix.zuul: INFO
