hystrix:
  command:
    default:
      circuitBreaker:
        enabled: true
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 30000
  threadpool:
    default:
      coreSize: 100
      maxQueueSize: 10000
      queueSizeRejectionThreshold: 10000

ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 5000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
        path: /uaa/**
        url: ${AUTH_SERVICE_URI:http://localhost:5000}
        stripPrefix: false
        sensitiveHeaders:

    account-service:
        path: /accounts/**
        serviceId: account-service
        stripPrefix: false
        sensitiveHeaders:

    statistics-service:
        path: /statistics/**
        serviceId: statistics-service
        stripPrefix: false
        sensitiveHeaders:

    notification-service:
        path: /notifications/**
        serviceId: notification-service
        stripPrefix: false
        sensitiveHeaders:

server:
  port: 4000
