security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: ${STATISTICS_SERVICE_PASSWORD}
      accessTokenUri: ${AUTH_SERVICE_URI:http://auth-service:5000}/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:statistics-mongodb}
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017

server:
  servlet:
    context-path: /statistics
  port: 7001

rates:
  url: https://api.exchangeratesapi.io


feign:
  hystrix:
    enabled: false